apiVersion : apps/v1
kind: Deployment
metadata:
  name: njsdemoapp2 
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: njsdemoapp2
  template:
    metadata:
      labels:
        app: njsdemoapp2 
    spec:
      containers:
        - name: njsdemoapp2 
          image: gpatfacr1.azurecr.io/njsdemoapp2:294
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
